[theme]
base = "light"
primaryColor = "#0052CC"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false